// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	// NFTs that are listed in marketplace
	Listings          []Listing        `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings"`
	ListingCount      uint64           `protobuf:"varint,2,opt,name=ListingCount,proto3" json:"ListingCount,omitempty"`
	Params            Params           `protobuf:"bytes,3,opt,name=params,proto3" json:"params"`
	Auctions          []AuctionListing `protobuf:"bytes,4,rep,name=auctions,proto3" json:"auctions"`
	Bids              []Bid            `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids"`
	NextAuctionNumber uint64           `protobuf:"varint,6,opt,name=next_auction_number,json=nextAuctionNumber,proto3" json:"next_auction_number,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_95d6349590cf6647, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetListings() []Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func (m *GenesisState) GetListingCount() uint64 {
	if m != nil {
		return m.ListingCount
	}
	return 0
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetAuctions() []AuctionListing {
	if m != nil {
		return m.Auctions
	}
	return nil
}

func (m *GenesisState) GetBids() []Bid {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *GenesisState) GetNextAuctionNumber() uint64 {
	if m != nil {
		return m.NextAuctionNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "OmniFlix.marketplace.v1beta1.GenesisState")
}

func init() { proto.RegisterFile("marketplace/v1beta1/genesis.proto", fileDescriptor_95d6349590cf6647) }

var fileDescriptor_95d6349590cf6647 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4f, 0xfa, 0x30,
	0x18, 0xc7, 0x37, 0xd8, 0x8f, 0x90, 0xc2, 0xe5, 0x57, 0x3d, 0x2c, 0xc4, 0xd4, 0x41, 0x34, 0xe1,
	0x60, 0xba, 0x00, 0x47, 0x4f, 0xce, 0x44, 0x2e, 0x8a, 0x06, 0x6f, 0x5e, 0x48, 0x07, 0xcd, 0x6c,
	0x64, 0xed, 0xb2, 0x76, 0x06, 0xdf, 0x85, 0x2f, 0x8b, 0x23, 0x47, 0x4f, 0xc6, 0xb0, 0xb7, 0xe1,
	0xc1, 0xd0, 0x15, 0x03, 0x86, 0xec, 0xb6, 0xf5, 0xf9, 0x7c, 0xff, 0x3c, 0x79, 0x40, 0x3b, 0x26,
	0xe9, 0x0b, 0x55, 0xc9, 0x9c, 0x4c, 0xa9, 0xff, 0xda, 0x0b, 0xa9, 0x22, 0x3d, 0x3f, 0xa2, 0x9c,
	0x4a, 0x26, 0x71, 0x92, 0x0a, 0x25, 0xe0, 0xc9, 0x7d, 0xcc, 0xd9, 0xcd, 0x9c, 0x2d, 0xf0, 0x0e,
	0x8b, 0x0d, 0xdb, 0x3a, 0x8e, 0x44, 0x24, 0x34, 0xe8, 0x6f, 0xbe, 0x0a, 0x4d, 0xeb, 0xa0, 0xed,
	0x9c, 0x49, 0xc5, 0x78, 0x54, 0x86, 0x90, 0x6c, 0xaa, 0x98, 0xe0, 0x06, 0xf1, 0x0e, 0x21, 0x09,
	0x49, 0x49, 0x6c, 0xba, 0x75, 0xbe, 0x2b, 0xa0, 0x39, 0x2c, 0xda, 0x3e, 0x2a, 0xa2, 0x28, 0x1c,
	0x82, 0xba, 0x89, 0x91, 0xae, 0xed, 0x55, 0xbb, 0x8d, 0xfe, 0x39, 0x2e, 0xeb, 0x8f, 0x6f, 0x0b,
	0x3a, 0x70, 0x96, 0x9f, 0xa7, 0xd6, 0xf8, 0x57, 0x0c, 0x3b, 0xa0, 0x69, 0x46, 0xd7, 0x22, 0xe3,
	0xca, 0xad, 0x78, 0x76, 0xd7, 0x19, 0xef, 0xbd, 0xc1, 0x00, 0xd4, 0x8a, 0x36, 0x6e, 0xd5, 0xb3,
	0xbb, 0x8d, 0xfe, 0x59, 0x79, 0xd4, 0x83, 0x66, 0x4d, 0x92, 0x51, 0xc2, 0x11, 0xa8, 0x9b, 0xa5,
	0xa5, 0xeb, 0xe8, 0xc2, 0x17, 0xe5, 0x2e, 0x57, 0x05, 0xfd, 0xa7, 0xf7, 0xd6, 0x03, 0x5e, 0x02,
	0x27, 0x64, 0x33, 0xe9, 0xfe, 0xd3, 0x5e, 0xed, 0x72, 0xaf, 0x80, 0xcd, 0x8c, 0x81, 0x16, 0x41,
	0x0c, 0x8e, 0x38, 0x5d, 0xa8, 0x89, 0x71, 0x9b, 0xf0, 0x2c, 0x0e, 0x69, 0xea, 0xd6, 0xf4, 0xee,
	0xff, 0x37, 0x23, 0x93, 0x3e, 0xd2, 0x83, 0xe0, 0x6e, 0xb9, 0x46, 0xf6, 0x6a, 0x8d, 0xec, 0xaf,
	0x35, 0xb2, 0xdf, 0x73, 0x64, 0xad, 0x72, 0x64, 0x7d, 0xe4, 0xc8, 0x7a, 0x1a, 0x44, 0x4c, 0x3d,
	0x67, 0x21, 0x9e, 0x8a, 0xd8, 0xdf, 0x56, 0xf0, 0x77, 0xcf, 0xb9, 0xff, 0xa7, 0xde, 0x12, 0x2a,
	0xc3, 0x9a, 0x3e, 0xea, 0xe0, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x4f, 0xac, 0x9f, 0x95, 0x02,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextAuctionNumber != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextAuctionNumber))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Bids) > 0 {
		for iNdEx := len(m.Bids) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Bids[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Auctions) > 0 {
		for iNdEx := len(m.Auctions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Auctions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ListingCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ListingCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Listings) > 0 {
		for iNdEx := len(m.Listings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Listings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Listings) > 0 {
		for _, e := range m.Listings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ListingCount != 0 {
		n += 1 + sovGenesis(uint64(m.ListingCount))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Auctions) > 0 {
		for _, e := range m.Auctions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Bids) > 0 {
		for _, e := range m.Bids {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextAuctionNumber != 0 {
		n += 1 + sovGenesis(uint64(m.NextAuctionNumber))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Listings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Listings = append(m.Listings, Listing{})
			if err := m.Listings[len(m.Listings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListingCount", wireType)
			}
			m.ListingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ListingCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auctions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auctions = append(m.Auctions, AuctionListing{})
			if err := m.Auctions[len(m.Auctions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bids", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bids = append(m.Bids, Bid{})
			if err := m.Bids[len(m.Bids)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextAuctionNumber", wireType)
			}
			m.NextAuctionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextAuctionNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
