// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: OmniFlix/medianode/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the medianode module's genesis state
type GenesisState struct {
	// params defines all the parameters of the module
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// media_nodes is the list of registered media nodes
	MediaNodes []MediaNode `protobuf:"bytes,2,rep,name=media_nodes,json=mediaNodes,proto3" json:"media_nodes"`
	Deposits   []Deposit   `protobuf:"bytes,3,rep,name=deposits,proto3" json:"deposits"`
	// leases is the list of active leases
	Leases []Lease `protobuf:"bytes,4,rep,name=leases,proto3" json:"leases"`
	// last_node_id is the last used media node ID
	LastNodeId uint64 `protobuf:"varint,5,opt,name=last_node_id,json=lastNodeId,proto3" json:"last_node_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ee63eaf92493f5e, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMediaNodes() []MediaNode {
	if m != nil {
		return m.MediaNodes
	}
	return nil
}

func (m *GenesisState) GetDeposits() []Deposit {
	if m != nil {
		return m.Deposits
	}
	return nil
}

func (m *GenesisState) GetLeases() []Lease {
	if m != nil {
		return m.Leases
	}
	return nil
}

func (m *GenesisState) GetLastNodeId() uint64 {
	if m != nil {
		return m.LastNodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "OmniFlix.medianode.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("OmniFlix/medianode/v1beta1/genesis.proto", fileDescriptor_1ee63eaf92493f5e)
}

var fileDescriptor_1ee63eaf92493f5e = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x1c, 0xc6, 0xdb, 0x6d, 0xbf, 0xf1, 0x23, 0xdb, 0xa9, 0x78, 0x28, 0x3b, 0xd4, 0x3a, 0x11, 0x8b,
	0x87, 0x84, 0x4d, 0xf1, 0xaa, 0x0c, 0xff, 0x20, 0xcc, 0x29, 0xf3, 0xe6, 0x65, 0xa4, 0x26, 0x76,
	0x81, 0xa6, 0x29, 0x4b, 0x36, 0xe6, 0xbb, 0xf0, 0x65, 0xed, 0xb8, 0xa3, 0x27, 0x91, 0xed, 0x8d,
	0x48, 0x92, 0xae, 0x7a, 0xb1, 0xb7, 0xf0, 0xe5, 0xf3, 0x7c, 0x78, 0xc2, 0x03, 0xa2, 0x07, 0x9e,
	0xb1, 0x9b, 0x94, 0x2d, 0x11, 0xa7, 0x84, 0xe1, 0x4c, 0x10, 0x8a, 0x16, 0xbd, 0x98, 0x2a, 0xdc,
	0x43, 0x09, 0xcd, 0xa8, 0x64, 0x12, 0xe6, 0x33, 0xa1, 0x84, 0xd7, 0xd9, 0x91, 0xb0, 0x24, 0x61,
	0x41, 0x76, 0xf6, 0x12, 0x91, 0x08, 0x83, 0x21, 0xfd, 0xb2, 0x89, 0xce, 0x49, 0x85, 0xfb, 0xc7,
	0x61, 0xd9, 0xe3, 0x0a, 0x36, 0xc7, 0x33, 0xcc, 0x8b, 0x1a, 0xdd, 0x55, 0x0d, 0xb4, 0x6f, 0x6d,
	0xb1, 0x27, 0x85, 0x15, 0xf5, 0x2e, 0x41, 0xd3, 0x02, 0xbe, 0x1b, 0xba, 0x51, 0xab, 0xdf, 0x85,
	0x7f, 0x17, 0x85, 0x8f, 0x86, 0x1c, 0x34, 0x56, 0x9f, 0xfb, 0xce, 0xb8, 0xc8, 0x79, 0x43, 0xd0,
	0x32, 0xe4, 0x44, 0xa3, 0xd2, 0xaf, 0x85, 0xf5, 0xa8, 0xd5, 0x3f, 0xaa, 0xd2, 0xdc, 0xeb, 0xcb,
	0x48, 0x10, 0x5a, 0x98, 0x00, 0xdf, 0x1d, 0xa4, 0x77, 0x0d, 0xfe, 0x13, 0x9a, 0x0b, 0xc9, 0x94,
	0xf4, 0xeb, 0x46, 0x75, 0x58, 0xa5, 0xba, 0xb2, 0x6c, 0x21, 0x2a, 0xa3, 0xde, 0x05, 0x68, 0xa6,
	0x14, 0x4b, 0x2a, 0xfd, 0x86, 0x91, 0x1c, 0x54, 0x49, 0x86, 0x9a, 0xdc, 0xfd, 0xca, 0xc6, 0xbc,
	0x10, 0xb4, 0x53, 0x2c, 0x95, 0xf9, 0xd4, 0x84, 0x11, 0xff, 0x5f, 0xe8, 0x46, 0x8d, 0x31, 0xd0,
	0x37, 0x5d, 0xf4, 0x8e, 0x0c, 0x46, 0xab, 0x4d, 0xe0, 0xae, 0x37, 0x81, 0xfb, 0xb5, 0x09, 0xdc,
	0xf7, 0x6d, 0xe0, 0xac, 0xb7, 0x81, 0xf3, 0xb1, 0x0d, 0x9c, 0xe7, 0xb3, 0x84, 0xa9, 0xe9, 0x3c,
	0x86, 0x2f, 0x82, 0xa3, 0x72, 0x18, 0xc1, 0x33, 0xf6, 0x9a, 0xb2, 0xe5, 0x74, 0x1e, 0xa3, 0xc5,
	0x39, 0xfa, 0xbd, 0x94, 0x7a, 0xcb, 0xa9, 0x8c, 0x9b, 0x66, 0xa1, 0xd3, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x18, 0x86, 0x63, 0x54, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastNodeId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastNodeId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Leases) > 0 {
		for iNdEx := len(m.Leases) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Leases[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Deposits) > 0 {
		for iNdEx := len(m.Deposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Deposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MediaNodes) > 0 {
		for iNdEx := len(m.MediaNodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MediaNodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MediaNodes) > 0 {
		for _, e := range m.MediaNodes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Deposits) > 0 {
		for _, e := range m.Deposits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Leases) > 0 {
		for _, e := range m.Leases {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.LastNodeId != 0 {
		n += 1 + sovGenesis(uint64(m.LastNodeId))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaNodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MediaNodes = append(m.MediaNodes, MediaNode{})
			if err := m.MediaNodes[len(m.MediaNodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposits = append(m.Deposits, Deposit{})
			if err := m.Deposits[len(m.Deposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leases", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leases = append(m.Leases, Lease{})
			if err := m.Leases[len(m.Leases)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastNodeId", wireType)
			}
			m.LastNodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastNodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
