version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000uflix
- name: bob
  coins:
  - 100000000uflix
faucet:
  name: bob
  coins:
  - 100000uflix
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 10000000uflix
