// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: OmniFlix/itc/v1/itc.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_gogo_protobuf_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DistributionType int32

const (
	DISTRIBUTION_TYPE_INSTANT DistributionType = 0
	DISTRIBUTION_TYPE_STREAM  DistributionType = 1
)

var DistributionType_name = map[int32]string{
	0: "DISTRIBUTION_TYPE_INSTANT",
	1: "DISTRIBUTION_TYPE_STREAM",
}

var DistributionType_value = map[string]int32{
	"DISTRIBUTION_TYPE_INSTANT": 0,
	"DISTRIBUTION_TYPE_STREAM":  1,
}

func (x DistributionType) String() string {
	return proto.EnumName(DistributionType_name, int32(x))
}

func (DistributionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{0}
}

type InteractionType int32

const (
	INTERACTION_TYPE_BURN     InteractionType = 0
	INTERACTION_TYPE_TRANSFER InteractionType = 1
	INTERACTION_TYPE_HOLD     InteractionType = 2
)

var InteractionType_name = map[int32]string{
	0: "INTERACTION_TYPE_BURN",
	1: "INTERACTION_TYPE_TRANSFER",
	2: "INTERACTION_TYPE_HOLD",
}

var InteractionType_value = map[string]int32{
	"INTERACTION_TYPE_BURN":     0,
	"INTERACTION_TYPE_TRANSFER": 1,
	"INTERACTION_TYPE_HOLD":     2,
}

func (x InteractionType) String() string {
	return proto.EnumName(InteractionType_name, int32(x))
}

func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{1}
}

type CampaignStatus int32

const (
	CAMPAIGN_STATUS_UNSPECIFIED CampaignStatus = 0
	CAMPAIGN_STATUS_INACTIVE    CampaignStatus = 1
	CAMPAIGN_STATUS_ACTIVE      CampaignStatus = 2
)

var CampaignStatus_name = map[int32]string{
	0: "CAMPAIGN_STATUS_UNSPECIFIED",
	1: "CAMPAIGN_STATUS_INACTIVE",
	2: "CAMPAIGN_STATUS_ACTIVE",
}

var CampaignStatus_value = map[string]int32{
	"CAMPAIGN_STATUS_UNSPECIFIED": 0,
	"CAMPAIGN_STATUS_INACTIVE":    1,
	"CAMPAIGN_STATUS_ACTIVE":      2,
}

func (x CampaignStatus) String() string {
	return proto.EnumName(CampaignStatus_name, int32(x))
}

func (CampaignStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{2}
}

type ClaimType int32

const (
	CLAIM_TYPE_FT         ClaimType = 0
	CLAIM_TYPE_NFT        ClaimType = 1
	CLAIM_TYPE_FT_AND_NFT ClaimType = 2
)

var ClaimType_name = map[int32]string{
	0: "CLAIM_TYPE_FT",
	1: "CLAIM_TYPE_NFT",
	2: "CLAIM_TYPE_FT_AND_NFT",
}

var ClaimType_value = map[string]int32{
	"CLAIM_TYPE_FT":         0,
	"CLAIM_TYPE_NFT":        1,
	"CLAIM_TYPE_FT_AND_NFT": 2,
}

func (x ClaimType) String() string {
	return proto.EnumName(ClaimType_name, int32(x))
}

func (ClaimType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{3}
}

type Campaign struct {
	Id               uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime        time.Time       `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	EndTime          time.Time       `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	Creator          string          `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	NftDenomId       string          `protobuf:"bytes,7,opt,name=nft_denom_id,json=nftDenomId,proto3" json:"nft_denom_id,omitempty" yaml:"nft_denom_id"`
	MaxAllowedClaims uint64          `protobuf:"varint,8,opt,name=max_allowed_claims,json=maxAllowedClaims,proto3" json:"max_allowed_claims,omitempty" yaml:"max_allowed_claims"`
	Interaction      InteractionType `protobuf:"varint,9,opt,name=interaction,proto3,enum=OmniFlix.itc.v1.InteractionType" json:"interaction,omitempty"`
	ClaimType        ClaimType       `protobuf:"varint,10,opt,name=claim_type,json=claimType,proto3,enum=OmniFlix.itc.v1.ClaimType" json:"claim_type,omitempty"`
	TokensPerClaim   types.Coin      `protobuf:"bytes,11,opt,name=tokens_per_claim,json=tokensPerClaim,proto3" json:"tokens_per_claim" yaml:"tokens_per_claim"`
	TotalTokens      types.Coin      `protobuf:"bytes,12,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens" yaml:"total_tokens"`
	AvailableTokens  types.Coin      `protobuf:"bytes,13,opt,name=available_tokens,json=availableTokens,proto3" json:"available_tokens" yaml:"available_tokens"`
	ReceivedNftIds   []string        `protobuf:"bytes,14,rep,name=received_nft_ids,json=receivedNftIds,proto3" json:"received_nft_ids,omitempty" yaml:"received_nft_ids"`
	NftMintDetails   *NFTDetails     `protobuf:"bytes,15,opt,name=nft_mint_details,json=nftMintDetails,proto3" json:"nft_mint_details,omitempty" yaml:"nft_mint_details"`
	Distribution     *Distribution   `protobuf:"bytes,16,opt,name=distribution,proto3" json:"distribution,omitempty" yaml:"distribution"`
	MintCount        uint64          `protobuf:"varint,17,opt,name=mint_count,json=mintCount,proto3" json:"mint_count,omitempty" yaml:"mint_count"`
	ClaimCount       uint64          `protobuf:"varint,18,opt,name=claim_count,json=claimCount,proto3" json:"claim_count,omitempty" yaml:"claim_count"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{0}
}
func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return m.Size()
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

type Distribution struct {
	Type           DistributionType `protobuf:"varint,1,opt,name=type,proto3,enum=OmniFlix.itc.v1.DistributionType" json:"type,omitempty"`
	StreamDuration time.Duration    `protobuf:"bytes,2,opt,name=stream_duration,json=streamDuration,proto3,stdduration" json:"stream_duration"`
}

func (m *Distribution) Reset()         { *m = Distribution{} }
func (m *Distribution) String() string { return proto.CompactTextString(m) }
func (*Distribution) ProtoMessage()    {}
func (*Distribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{1}
}
func (m *Distribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Distribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Distribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Distribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distribution.Merge(m, src)
}
func (m *Distribution) XXX_Size() int {
	return m.Size()
}
func (m *Distribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Distribution.DiscardUnknown(m)
}

var xxx_messageInfo_Distribution proto.InternalMessageInfo

type NFTDetails struct {
	DenomId      string                                 `protobuf:"bytes,1,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty"`
	Name         string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string                                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MediaUri     string                                 `protobuf:"bytes,4,opt,name=media_uri,json=mediaUri,proto3" json:"media_uri,omitempty"`
	PreviewUri   string                                 `protobuf:"bytes,5,opt,name=preview_uri,json=previewUri,proto3" json:"preview_uri,omitempty"`
	RoyaltyShare github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=royalty_share,json=royaltyShare,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"royalty_share" yaml:"royalty_share"`
	Transferable bool                                   `protobuf:"varint,7,opt,name=transferable,proto3" json:"transferable,omitempty"`
	Extensible   bool                                   `protobuf:"varint,8,opt,name=extensible,proto3" json:"extensible,omitempty"`
	Nsfw         bool                                   `protobuf:"varint,9,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Data         string                                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	UriHash      string                                 `protobuf:"bytes,11,opt,name=uri_hash,json=uriHash,proto3" json:"uri_hash,omitempty"`
}

func (m *NFTDetails) Reset()         { *m = NFTDetails{} }
func (m *NFTDetails) String() string { return proto.CompactTextString(m) }
func (*NFTDetails) ProtoMessage()    {}
func (*NFTDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{2}
}
func (m *NFTDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NFTDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NFTDetails.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NFTDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NFTDetails.Merge(m, src)
}
func (m *NFTDetails) XXX_Size() int {
	return m.Size()
}
func (m *NFTDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_NFTDetails.DiscardUnknown(m)
}

var xxx_messageInfo_NFTDetails proto.InternalMessageInfo

type Claim struct {
	CampaignId  uint64          `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Address     string          `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	NftId       string          `protobuf:"bytes,3,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
	Interaction InteractionType `protobuf:"varint,4,opt,name=interaction,proto3,enum=OmniFlix.itc.v1.InteractionType" json:"interaction,omitempty"`
}

func (m *Claim) Reset()         { *m = Claim{} }
func (m *Claim) String() string { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()    {}
func (*Claim) Descriptor() ([]byte, []int) {
	return fileDescriptor_bab9913014645745, []int{3}
}
func (m *Claim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Claim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Claim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Claim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claim.Merge(m, src)
}
func (m *Claim) XXX_Size() int {
	return m.Size()
}
func (m *Claim) XXX_DiscardUnknown() {
	xxx_messageInfo_Claim.DiscardUnknown(m)
}

var xxx_messageInfo_Claim proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("OmniFlix.itc.v1.DistributionType", DistributionType_name, DistributionType_value)
	proto.RegisterEnum("OmniFlix.itc.v1.InteractionType", InteractionType_name, InteractionType_value)
	proto.RegisterEnum("OmniFlix.itc.v1.CampaignStatus", CampaignStatus_name, CampaignStatus_value)
	proto.RegisterEnum("OmniFlix.itc.v1.ClaimType", ClaimType_name, ClaimType_value)
	proto.RegisterType((*Campaign)(nil), "OmniFlix.itc.v1.Campaign")
	proto.RegisterType((*Distribution)(nil), "OmniFlix.itc.v1.Distribution")
	proto.RegisterType((*NFTDetails)(nil), "OmniFlix.itc.v1.NFTDetails")
	proto.RegisterType((*Claim)(nil), "OmniFlix.itc.v1.Claim")
}

func init() { proto.RegisterFile("OmniFlix/itc/v1/itc.proto", fileDescriptor_bab9913014645745) }

var fileDescriptor_bab9913014645745 = []byte{
	// 1220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0xdb, 0x36,
	0x18, 0xb6, 0xd2, 0xa4, 0xb1, 0x5f, 0xa7, 0x8e, 0xcb, 0x7e, 0x29, 0xc9, 0x62, 0x7b, 0x3a, 0x0c,
	0x41, 0x80, 0xc9, 0x48, 0xb7, 0x61, 0xe8, 0x6e, 0xfe, 0x5c, 0x85, 0x35, 0x4a, 0x40, 0x2b, 0xc3,
	0xda, 0x8b, 0x40, 0x4b, 0x74, 0x42, 0xc4, 0x92, 0x0c, 0x89, 0x76, 0x93, 0x5f, 0xb1, 0x02, 0xbb,
	0xec, 0xb2, 0x9f, 0xb2, 0x7b, 0x8f, 0x3d, 0x0e, 0x3b, 0x78, 0x6b, 0xfb, 0x0f, 0xf2, 0x0b, 0x06,
	0x92, 0x52, 0xac, 0x3a, 0xc3, 0x8a, 0xf5, 0x24, 0xf2, 0xfd, 0x78, 0xde, 0x97, 0xe4, 0xc3, 0x87,
	0x82, 0xad, 0xa3, 0x20, 0x64, 0xfd, 0x31, 0xbb, 0x68, 0x32, 0xee, 0x35, 0x67, 0x07, 0xe2, 0x63,
	0x4e, 0xe2, 0x88, 0x47, 0x68, 0x33, 0x73, 0x99, 0xc2, 0x36, 0x3b, 0xd8, 0xae, 0x79, 0x51, 0x12,
	0x44, 0x49, 0x73, 0x48, 0x12, 0xda, 0x9c, 0x1d, 0x0c, 0x29, 0x27, 0x07, 0x4d, 0x2f, 0x62, 0xa1,
	0x4a, 0xd8, 0xbe, 0x7f, 0x1a, 0x9d, 0x46, 0x72, 0xd8, 0x14, 0xa3, 0xd4, 0x5a, 0x3f, 0x8d, 0xa2,
	0xd3, 0x31, 0x6d, 0xca, 0xd9, 0x70, 0x3a, 0x6a, 0x72, 0x16, 0xd0, 0x84, 0x93, 0x60, 0x92, 0x06,
	0xd4, 0x96, 0x03, 0xfc, 0x69, 0x4c, 0x38, 0x8b, 0x52, 0x58, 0xe3, 0xf7, 0x12, 0x14, 0x3b, 0x24,
	0x98, 0x10, 0x76, 0x1a, 0xa2, 0x0a, 0xac, 0x30, 0x5f, 0xd7, 0x1a, 0xda, 0xde, 0x2a, 0x5e, 0x61,
	0x3e, 0x42, 0xb0, 0x1a, 0x92, 0x80, 0xea, 0x2b, 0x0d, 0x6d, 0xaf, 0x84, 0xe5, 0x18, 0x35, 0xa0,
	0xec, 0xd3, 0xc4, 0x8b, 0xd9, 0x44, 0xa0, 0xe8, 0xb7, 0xa4, 0x2b, 0x6f, 0x42, 0x3f, 0x01, 0x24,
	0x9c, 0xc4, 0xdc, 0x15, 0xbd, 0xe8, 0xab, 0x0d, 0x6d, 0xaf, 0xfc, 0x78, 0xdb, 0x54, 0x7d, 0x98,
	0x59, 0x1f, 0xa6, 0x93, 0x35, 0xda, 0xde, 0x7d, 0x3d, 0xaf, 0x17, 0xae, 0xe6, 0xf5, 0xbb, 0x97,
	0x24, 0x18, 0x7f, 0x67, 0x2c, 0x72, 0x8d, 0x57, 0x7f, 0xd5, 0x35, 0x5c, 0x92, 0x06, 0x11, 0x8e,
	0x30, 0x14, 0x69, 0xe8, 0x2b, 0xdc, 0xb5, 0x8f, 0xe2, 0xee, 0xa4, 0xb8, 0x9b, 0x0a, 0x37, 0xcb,
	0x54, 0xa8, 0xeb, 0x34, 0xf4, 0x25, 0xa6, 0x0e, 0xeb, 0x5e, 0x4c, 0x09, 0x8f, 0x62, 0xfd, 0xb6,
	0x5c, 0x4b, 0x36, 0x45, 0x4f, 0x60, 0x23, 0x1c, 0x71, 0xd7, 0xa7, 0x61, 0x14, 0xb8, 0xcc, 0xd7,
	0xd7, 0x85, 0xbb, 0xfd, 0xe8, 0x6a, 0x5e, 0xbf, 0xa7, 0x10, 0xf3, 0x5e, 0x03, 0x43, 0x38, 0xe2,
	0x5d, 0x31, 0xb3, 0x7c, 0xf4, 0x03, 0xa0, 0x80, 0x5c, 0xb8, 0x64, 0x3c, 0x8e, 0x5e, 0x52, 0xdf,
	0xf5, 0xc6, 0x84, 0x05, 0x89, 0x5e, 0x14, 0x1b, 0xdb, 0xde, 0xbd, 0x9a, 0xd7, 0xb7, 0x14, 0xc0,
	0xcd, 0x18, 0x03, 0x57, 0x03, 0x72, 0xd1, 0x52, 0xb6, 0x8e, 0x34, 0xa1, 0x36, 0x94, 0x59, 0xc8,
	0x69, 0x4c, 0x3c, 0xb9, 0xe3, 0xa5, 0x86, 0xb6, 0x57, 0x79, 0xdc, 0x30, 0x97, 0x08, 0x64, 0x5a,
	0x8b, 0x18, 0xe7, 0x72, 0x42, 0x71, 0x3e, 0x09, 0x3d, 0x01, 0x90, 0x05, 0x5c, 0x7e, 0x39, 0xa1,
	0x3a, 0x48, 0x88, 0xed, 0x1b, 0x10, 0xb2, 0xa0, 0x4c, 0x2e, 0x79, 0xd9, 0x10, 0xf9, 0x50, 0xe5,
	0xd1, 0x39, 0x0d, 0x13, 0x77, 0x42, 0x63, 0xd5, 0xa6, 0x5e, 0x96, 0x9b, 0xbf, 0x65, 0x2a, 0xce,
	0x9a, 0x82, 0xb3, 0x66, 0xca, 0x59, 0xb3, 0x13, 0xb1, 0xb0, 0x5d, 0x4f, 0xf7, 0xfe, 0x91, 0x5a,
	0xe8, 0x32, 0x80, 0x81, 0x2b, 0xca, 0x74, 0x4c, 0x63, 0x59, 0x14, 0x3d, 0x87, 0x0d, 0x1e, 0x71,
	0x32, 0x76, 0x95, 0x5d, 0xdf, 0xf8, 0x58, 0x85, 0xec, 0x74, 0xef, 0x65, 0x15, 0x16, 0xc9, 0x06,
	0x2e, 0xcb, 0xa9, 0x23, 0x67, 0x88, 0x42, 0x95, 0xcc, 0x08, 0x1b, 0x93, 0xe1, 0x98, 0x66, 0xf0,
	0x77, 0xfe, 0xe7, 0x02, 0x96, 0x01, 0x0c, 0xbc, 0x79, 0x6d, 0x4a, 0xcb, 0xf4, 0xa0, 0x1a, 0x53,
	0x8f, 0xb2, 0x19, 0xf5, 0x5d, 0xc1, 0x0c, 0xe6, 0x27, 0x7a, 0xa5, 0x71, 0x6b, 0xaf, 0xd4, 0xde,
	0x59, 0xe0, 0x2c, 0x47, 0x18, 0xb8, 0x92, 0x99, 0xec, 0x11, 0xb7, 0xfc, 0x04, 0x0d, 0xa1, 0x2a,
	0x7c, 0x01, 0x0b, 0x05, 0xb9, 0x38, 0x61, 0xe3, 0x44, 0xdf, 0x94, 0xdd, 0xee, 0xdc, 0x38, 0x2f,
	0xbb, 0xef, 0x74, 0x55, 0x48, 0xbe, 0xc6, 0x72, 0xba, 0x81, 0x2b, 0xe1, 0x88, 0x1f, 0xb2, 0x90,
	0xa7, 0xc1, 0xe8, 0x05, 0x6c, 0xf8, 0x2c, 0xe1, 0x31, 0x1b, 0x4e, 0x25, 0xa5, 0xaa, 0x12, 0x7f,
	0xf7, 0x06, 0x7e, 0x37, 0x17, 0x94, 0x27, 0x7e, 0x3e, 0xd9, 0xc0, 0x1f, 0x60, 0xa1, 0xaf, 0x01,
	0x64, 0x71, 0x2f, 0x9a, 0x86, 0x5c, 0xbf, 0x2b, 0x29, 0xff, 0x60, 0x71, 0xbb, 0x17, 0x3e, 0x03,
	0x97, 0xc4, 0xa4, 0x23, 0xc6, 0xe8, 0x5b, 0x28, 0x2b, 0x7e, 0xaa, 0x34, 0x24, 0xd3, 0x1e, 0x5e,
	0xcd, 0xeb, 0x48, 0xa5, 0xe5, 0x9c, 0x06, 0x56, 0x54, 0x96, 0x89, 0xc6, 0x2f, 0x1a, 0x6c, 0xe4,
	0xdb, 0x44, 0xdf, 0xc0, 0xaa, 0xe4, 0xb8, 0x26, 0x39, 0xfe, 0xf9, 0x7f, 0xae, 0x49, 0x52, 0x5d,
	0x86, 0xa3, 0x67, 0xb0, 0x99, 0xf0, 0x98, 0x92, 0xc0, 0xcd, 0x04, 0x52, 0xaa, 0x9e, 0xe0, 0xc8,
	0xb2, 0xc2, 0x74, 0xd3, 0x80, 0x76, 0x51, 0x70, 0xe4, 0x57, 0xa1, 0x26, 0x15, 0x95, 0x9b, 0x79,
	0x8c, 0x9f, 0x6f, 0x01, 0x2c, 0x0e, 0x07, 0x6d, 0x41, 0xf1, 0x5a, 0x45, 0x34, 0x25, 0x32, 0x7e,
	0xaa, 0x14, 0x9f, 0x26, 0xb1, 0x3b, 0x50, 0x0a, 0xa8, 0xcf, 0x88, 0x3b, 0x8d, 0x99, 0x54, 0xd8,
	0x12, 0x2e, 0x4a, 0xc3, 0x49, 0xcc, 0x50, 0x1d, 0xca, 0x93, 0x98, 0xce, 0x18, 0x7d, 0x29, 0xdd,
	0x6b, 0xd2, 0x0d, 0xa9, 0x49, 0x04, 0x9c, 0xc3, 0x9d, 0x38, 0xba, 0x24, 0x63, 0x7e, 0xe9, 0x26,
	0x67, 0x24, 0xa6, 0x4a, 0xf8, 0xda, 0x7d, 0xb1, 0x9c, 0x3f, 0xe7, 0xf5, 0x2f, 0x4e, 0x19, 0x3f,
	0x9b, 0x0e, 0x4d, 0x2f, 0x0a, 0x9a, 0xe9, 0xa3, 0xa4, 0x3e, 0x5f, 0x26, 0xfe, 0x79, 0x53, 0xec,
	0x56, 0x62, 0x76, 0xa9, 0x77, 0x35, 0xaf, 0xdf, 0x4f, 0x49, 0x9d, 0x07, 0x33, 0xf0, 0x46, 0x3a,
	0x1f, 0x88, 0x29, 0x32, 0x60, 0x83, 0xc7, 0x24, 0x4c, 0x46, 0x34, 0x16, 0x97, 0x45, 0xaa, 0x68,
	0x11, 0x7f, 0x60, 0x43, 0x35, 0x00, 0x7a, 0xc1, 0x69, 0x98, 0x30, 0x11, 0x51, 0x94, 0x11, 0x39,
	0x8b, 0xdc, 0xa4, 0x64, 0xf4, 0x52, 0x4a, 0x5f, 0x11, 0xcb, 0xb1, 0xb0, 0xf9, 0x84, 0x13, 0xa9,
	0x65, 0x25, 0x2c, 0xc7, 0x62, 0x9f, 0xa7, 0x31, 0x73, 0xcf, 0x48, 0x72, 0x26, 0x25, 0xaa, 0x84,
	0xd7, 0xa7, 0x31, 0x7b, 0x4a, 0x92, 0x33, 0xe3, 0x37, 0x0d, 0xd6, 0x94, 0xd2, 0xd4, 0xa1, 0xec,
	0xa5, 0x0f, 0x9e, 0x7b, 0xfd, 0xda, 0x41, 0x66, 0xb2, 0x7c, 0xf1, 0x22, 0x10, 0xdf, 0x8f, 0x69,
	0x92, 0xa4, 0xa7, 0x92, 0x4d, 0xd1, 0x03, 0xb8, 0xad, 0xee, 0x6d, 0x7a, 0x26, 0x6b, 0xa1, 0xb8,
	0xb3, 0xcb, 0x02, 0xbd, 0xfa, 0x09, 0x02, 0xbd, 0x7f, 0x04, 0xd5, 0x65, 0x66, 0xa2, 0x5d, 0xd8,
	0xea, 0x5a, 0x03, 0x07, 0x5b, 0xed, 0x13, 0xc7, 0x3a, 0xb2, 0x5d, 0xe7, 0xf9, 0x71, 0xcf, 0xb5,
	0xec, 0x81, 0xd3, 0xb2, 0x9d, 0x6a, 0x01, 0x7d, 0x06, 0xfa, 0x4d, 0xf7, 0xc0, 0xc1, 0xbd, 0xd6,
	0x61, 0x55, 0xdb, 0x1f, 0xc1, 0xe6, 0x52, 0x41, 0xb4, 0x05, 0x0f, 0x2c, 0xdb, 0xe9, 0xe1, 0x56,
	0x67, 0x11, 0xdf, 0x3e, 0xc1, 0x76, 0xb5, 0x20, 0x4a, 0xdd, 0x70, 0x39, 0xb8, 0x65, 0x0f, 0xfa,
	0x3d, 0x5c, 0xd5, 0xfe, 0x35, 0xf3, 0xe9, 0xd1, 0xb3, 0x6e, 0x75, 0x65, 0xff, 0x1c, 0x2a, 0xd9,
	0xff, 0xc3, 0x80, 0x13, 0x3e, 0x4d, 0x50, 0x1d, 0x76, 0x3a, 0xad, 0xc3, 0xe3, 0x96, 0xf5, 0xbd,
	0xed, 0x0e, 0x9c, 0x96, 0x73, 0x32, 0x70, 0x4f, 0xec, 0xc1, 0x71, 0xaf, 0x63, 0xf5, 0xad, 0x5e,
	0x57, 0x35, 0xbe, 0x1c, 0x60, 0xd9, 0x02, 0xfa, 0xc7, 0x5e, 0x55, 0x43, 0xdb, 0xf0, 0x70, 0xd9,
	0x9b, 0xfa, 0x56, 0xf6, 0x0f, 0xa1, 0x74, 0xfd, 0x46, 0xa1, 0xbb, 0x70, 0xa7, 0xf3, 0xac, 0x65,
	0x1d, 0xaa, 0x76, 0xfa, 0x62, 0x4b, 0x10, 0x54, 0x72, 0x26, 0xbb, 0xef, 0xa8, 0xde, 0x3f, 0x08,
	0x73, 0x5b, 0x76, 0x57, 0xba, 0x56, 0xda, 0xc7, 0xaf, 0xdf, 0xd6, 0x0a, 0x6f, 0xde, 0xd6, 0x0a,
	0xaf, 0xdf, 0xd5, 0xb4, 0x37, 0xef, 0x6a, 0xda, 0xdf, 0xef, 0x6a, 0xda, 0xab, 0xf7, 0xb5, 0xc2,
	0x9b, 0xf7, 0xb5, 0xc2, 0x1f, 0xef, 0x6b, 0x85, 0x17, 0x66, 0xee, 0x2e, 0x5c, 0xff, 0xcc, 0x45,
	0x41, 0xc8, 0x46, 0x63, 0x76, 0x71, 0x36, 0x1d, 0x36, 0x67, 0x8f, 0x9b, 0xea, 0xef, 0x4e, 0xde,
	0x8b, 0xe1, 0x6d, 0xa9, 0x12, 0x5f, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x35, 0x7f, 0xf1, 0x13,
	0xfa, 0x09, 0x00, 0x00,
}

func (m *Campaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Campaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Campaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClaimCount != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.ClaimCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.MintCount != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.MintCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Distribution != nil {
		{
			size, err := m.Distribution.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintItc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.NftMintDetails != nil {
		{
			size, err := m.NftMintDetails.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintItc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7a
	}
	if len(m.ReceivedNftIds) > 0 {
		for iNdEx := len(m.ReceivedNftIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ReceivedNftIds[iNdEx])
			copy(dAtA[i:], m.ReceivedNftIds[iNdEx])
			i = encodeVarintItc(dAtA, i, uint64(len(m.ReceivedNftIds[iNdEx])))
			i--
			dAtA[i] = 0x72
		}
	}
	{
		size, err := m.AvailableTokens.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintItc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.TotalTokens.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintItc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size, err := m.TokensPerClaim.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintItc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.ClaimType != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.ClaimType))
		i--
		dAtA[i] = 0x50
	}
	if m.Interaction != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.Interaction))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxAllowedClaims != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.MaxAllowedClaims))
		i--
		dAtA[i] = 0x40
	}
	if len(m.NftDenomId) > 0 {
		i -= len(m.NftDenomId)
		copy(dAtA[i:], m.NftDenomId)
		i = encodeVarintItc(dAtA, i, uint64(len(m.NftDenomId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	n6, err6 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintItc(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x2a
	n7, err7 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintItc(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x22
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Distribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Distribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Distribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n8, err8 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.StreamDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.StreamDuration):])
	if err8 != nil {
		return 0, err8
	}
	i -= n8
	i = encodeVarintItc(dAtA, i, uint64(n8))
	i--
	dAtA[i] = 0x12
	if m.Type != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NFTDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NFTDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NFTDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UriHash) > 0 {
		i -= len(m.UriHash)
		copy(dAtA[i:], m.UriHash)
		i = encodeVarintItc(dAtA, i, uint64(len(m.UriHash)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x52
	}
	if m.Nsfw {
		i--
		if m.Nsfw {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.Extensible {
		i--
		if m.Extensible {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.Transferable {
		i--
		if m.Transferable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.RoyaltyShare.Size()
		i -= size
		if _, err := m.RoyaltyShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintItc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.PreviewUri) > 0 {
		i -= len(m.PreviewUri)
		copy(dAtA[i:], m.PreviewUri)
		i = encodeVarintItc(dAtA, i, uint64(len(m.PreviewUri)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MediaUri) > 0 {
		i -= len(m.MediaUri)
		copy(dAtA[i:], m.MediaUri)
		i = encodeVarintItc(dAtA, i, uint64(len(m.MediaUri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintItc(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Claim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Claim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Claim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Interaction != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.Interaction))
		i--
		dAtA[i] = 0x20
	}
	if len(m.NftId) > 0 {
		i -= len(m.NftId)
		copy(dAtA[i:], m.NftId)
		i = encodeVarintItc(dAtA, i, uint64(len(m.NftId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintItc(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.CampaignId != 0 {
		i = encodeVarintItc(dAtA, i, uint64(m.CampaignId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintItc(dAtA []byte, offset int, v uint64) int {
	offset -= sovItc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Campaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovItc(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovItc(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovItc(uint64(l))
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.NftDenomId)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	if m.MaxAllowedClaims != 0 {
		n += 1 + sovItc(uint64(m.MaxAllowedClaims))
	}
	if m.Interaction != 0 {
		n += 1 + sovItc(uint64(m.Interaction))
	}
	if m.ClaimType != 0 {
		n += 1 + sovItc(uint64(m.ClaimType))
	}
	l = m.TokensPerClaim.Size()
	n += 1 + l + sovItc(uint64(l))
	l = m.TotalTokens.Size()
	n += 1 + l + sovItc(uint64(l))
	l = m.AvailableTokens.Size()
	n += 1 + l + sovItc(uint64(l))
	if len(m.ReceivedNftIds) > 0 {
		for _, s := range m.ReceivedNftIds {
			l = len(s)
			n += 1 + l + sovItc(uint64(l))
		}
	}
	if m.NftMintDetails != nil {
		l = m.NftMintDetails.Size()
		n += 1 + l + sovItc(uint64(l))
	}
	if m.Distribution != nil {
		l = m.Distribution.Size()
		n += 2 + l + sovItc(uint64(l))
	}
	if m.MintCount != 0 {
		n += 2 + sovItc(uint64(m.MintCount))
	}
	if m.ClaimCount != 0 {
		n += 2 + sovItc(uint64(m.ClaimCount))
	}
	return n
}

func (m *Distribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovItc(uint64(m.Type))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.StreamDuration)
	n += 1 + l + sovItc(uint64(l))
	return n
}

func (m *NFTDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.MediaUri)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.PreviewUri)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = m.RoyaltyShare.Size()
	n += 1 + l + sovItc(uint64(l))
	if m.Transferable {
		n += 2
	}
	if m.Extensible {
		n += 2
	}
	if m.Nsfw {
		n += 2
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.UriHash)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	return n
}

func (m *Claim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CampaignId != 0 {
		n += 1 + sovItc(uint64(m.CampaignId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	l = len(m.NftId)
	if l > 0 {
		n += 1 + l + sovItc(uint64(l))
	}
	if m.Interaction != 0 {
		n += 1 + sovItc(uint64(m.Interaction))
	}
	return n
}

func sovItc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozItc(x uint64) (n int) {
	return sovItc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Campaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowItc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Campaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Campaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftDenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftDenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAllowedClaims", wireType)
			}
			m.MaxAllowedClaims = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAllowedClaims |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interaction", wireType)
			}
			m.Interaction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Interaction |= InteractionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimType", wireType)
			}
			m.ClaimType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimType |= ClaimType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokensPerClaim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokensPerClaim.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AvailableTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivedNftIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceivedNftIds = append(m.ReceivedNftIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftMintDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NftMintDetails == nil {
				m.NftMintDetails = &NFTDetails{}
			}
			if err := m.NftMintDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Distribution == nil {
				m.Distribution = &Distribution{}
			}
			if err := m.Distribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintCount", wireType)
			}
			m.MintCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimCount", wireType)
			}
			m.ClaimCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipItc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthItc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Distribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowItc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Distribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Distribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= DistributionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.StreamDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipItc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthItc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NFTDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowItc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NFTDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NFTDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MediaUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviewUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviewUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RoyaltyShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transferable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Transferable = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extensible", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Extensible = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nsfw", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Nsfw = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UriHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UriHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipItc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthItc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Claim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowItc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Claim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Claim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignId", wireType)
			}
			m.CampaignId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthItc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthItc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interaction", wireType)
			}
			m.Interaction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowItc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Interaction |= InteractionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipItc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthItc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipItc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowItc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowItc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowItc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthItc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupItc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthItc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthItc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowItc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupItc = fmt.Errorf("proto: unexpected end of group")
)
